### PR TITLE
update xonsh script and instructions

### PR DESCRIPTION
**Pull request by jfmontanaro**
As discussed on [atuin repo](https://github.com/atuinsh/atuin/pull/1375).

Summary of changes:
* Added duration to postcommand hook
* Switched main search operation to use `subproccess.run()` rather than running as an xonsh shell command - this a) allows us to capture stderr without needing a temporary file and b) avoids a weird broken-buffer state that results from running a fullscreen TUI and then programmatically editing the buffer
* Added support for immediately executing chosen command via `__atuin_accept__:` (like bash/zsh/fish)

I also didn't have any trouble getting the integration to work via just `execx($(atuin init xonsh))`, so I think (hope) the whole dance with an intermediate file might not be necessary?

### CODE REVIEW

**Comment by jfmontanaro** [comment]
I went ahead and rebased on upstream because it turns out that saving the duration via `atuin history end` is a relatively recent addition, so my post-exec hook was failing and I didn't even realize. (I originally was working against the latest release when coming up with the script, and when I opened this PR I just copied most of it over.)

**Comment by Matthieu-LAURENT39** [comment]
Sorry for the slow reply, i've been quite busy and this flew under my radar :sweat_smile: 
I would merge, but there are some merge conflicts, do you think you could take a look?
If you can't, i'll try to take a look this thursday

**Comment by Matthieu-LAURENT39** [comment]
In the end i ended up performing the merge by hand.
Really nice job by the way, i had no idea `.detype()` was a thing for `${}`, really clean way to allow the use of subprocess.run!

**Comment by jfmontanaro** [comment]
Thanks! Sorry about the merge conflicts, I should have realized just rebasing would cause the same conflicts to show up in the PR. Glad you sorted those out! :sweat_smile:

**Pull request merged**
